### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by louismonteiro** [louismonteiro/Phrase2Post#1]
- [ ] **Controller**
   - [x] User questionaire
   - [x] Get the text (lyrics)
   - [x] Split the text
   - [ ] Generate the images

- [x] Get the text
   - [x] Fetch random lyrics from random artist
   - [x] Fetch random lyrics from specific artist
   - [x] Return Lyrics
   

- [x] Split the text
   - [x] Split text into groups of 4 lines
   

- [ ] Generate the images
   - [ ] Setup font properties
   - [ ] Add text to image 
   - [ ] Add brand to image
